apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juicefs-gateway
  labels:
    app: juicefs-gateway
spec:
  rules:
    - host: juicefs.revelly.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juicefs-gateway
                port:
                  number: 9000
